import torch
import re
from threading import Thread
from transformers import AutoProcessor, AutoModelForCausalLM, TextIteratorStreamer

class GemmaAudioEngine:
    def __init__(self, model_path, device="cuda", compute_type="bfloat16"):
        print(f"Loading Gemma 4 Processor from {model_path}...")
        self.processor = AutoProcessor.from_pretrained(model_path)
        
        print(f"Loading Gemma 4 Model from {model_path} to {device}...")
        self.dtype = torch.bfloat16 if compute_type == "bfloat16" else torch.float16
        
        self.model = AutoModelForCausalLM.from_pretrained(
            model_path,
            trust_remote_code=True, 
            device_map=device,
            torch_dtype=self.dtype
        )
        self.model.eval()
        self.sample_rate = 16000 # Gemma native audio sample rate
        self.history = [] # holds rolling text turns
        
        # Save device for runtime tensor movement
        self.device = device 

    def _format_prompt(self, system_prompt):
        """Builds the prompt with strict language and format anchors."""
        
        # We determine the expected language baseline from history to anchor the prompt
        # (Defaulting to English if history is empty)
        expected_lang = "en"
        if len(self.history) > 0:
             last_response = self.history[-1]["content"][0]["text"]
             # Check if Devanagari characters dominated the last response
             if any('\u0900' <= c <= '\u097F' for c in last_response):
                 expected_lang = "hi"
                 
        anchor_rule = "Respond strictly using English text (Latin script)." if expected_lang == "en" else "Respond strictly using Hindi text (Devanagari script)."

        structured_prompt = (
            f"{system_prompt}\n\n"
            "You MUST format your output exactly like this:\n"
            "<Transcription> [Write exactly what the patient said in the audio] </Transcription>\n"
            f"<Language> {expected_lang} </Language>\n"
            f"<Response> [Write your clinical, empathetic response here. {anchor_rule}] </Response>"
        )
        return structured_prompt

    def generate_response_stream(self, audio_array, system_prompt):
        """
        Natively streams tokens out one-by-one using a generator.
        Replaces the old blocking return mechanism.
        """
        # 1. Format the prompt with cross-lingual guards
        final_prompt = self._format_prompt(system_prompt)
        
        # 2. Process inputs into tensors
        inputs = self.processor(audio=audio_array, text=final_prompt, return_tensors="pt").to(self.device)
        
        # 3. Setup the asynchronous streamer
        streamer = TextIteratorStreamer(self.processor.tokenizer, skip_prompt=True, skip_special_tokens=True)
        
        # 4. Configure generation kwargs
        generation_kwargs = dict(
            **inputs, 
            streamer=streamer, 
            max_new_tokens=512, # Increased slightly to ensure Hindi has enough token budget
            temperature=0.7,
            do_sample=True,
            top_p=0.95
        )
        
        # 5. Launch generation in a non-blocking background thread
        thread = Thread(target=self.model.generate, kwargs=generation_kwargs)
        thread.start()
        
        # 6. Yield tokens live as they are generated by the model
        for new_token in streamer:
            yield new_token
            
    def update_history(self, final_transcription, final_response):
        """Public helper to push verified strings back into history after the stream finishes."""
        if final_transcription and final_response:
             self.history.append({"role":"user", "content":[{"type":"text", "text":final_transcription}]})
             self.history.append({"role":"assistant", "content":[{"type":"text", "text":final_response}]})
