import torch
from threading import Thread
from transformers import AutoProcessor, AutoModelForCausalLM, TextIteratorStreamer

class GemmaAudioEngine:
    def __init__(self, model_path, device="cuda", compute_type="bfloat16"):
        print(f"Loading Multimodal Processor from {model_path}...")
        self.processor = AutoProcessor.from_pretrained(model_path)
        
        print(f"Loading Multimodal Model from {model_path} to {device}...")
        self.dtype = torch.bfloat16 if compute_type == "bfloat16" else torch.float16
        
        self.model = AutoModelForCausalLM.from_pretrained(
            model_path,
            trust_remote_code=True, 
            device_map=device,
            torch_dtype=self.dtype
        )
        self.model.eval()
        self.sample_rate = 16000 
        self.history = [] # Holds rolling text turns
        self.device = device 

    def _format_prompt(self, system_prompt):
        """Builds the prompt using the model's native chat template API."""
        
        expected_lang = "en"
        if len(self.history) > 0:
             last_response = self.history[-1]["content"]
             if any('\u0900' <= c <= '\u097F' for c in last_response):
                 expected_lang = "hi"
                 
        anchor_rule = "Respond strictly using English text (Latin script)." if expected_lang == "en" else "Respond strictly using Hindi text (Devanagari script)."

        structured_text = (
            f"{system_prompt}\n\n"
            "You MUST format your output exactly like this:\n"
            "<Transcription> [Write exactly what the patient said in the audio] </Transcription>\n"
            f"<Language> {expected_lang} </Language>\n"
            f"<Response> [Write your clinical, empathetic response here. {anchor_rule}] </Response>"
        )
        
        # Build the message chain starting with history
        messages = []
        for turn in self.history:
            # We ONLY append text history to avoid exploding multimodal tokens
            messages.append({"role": turn["role"], "content": [{"type": "text", "text": turn["content"]}]})
            
        # Append the CURRENT turn, which includes the <audio> tag
        messages.append({
            "role": "user",
            "content": [
                {"type": "audio"},
                {"type": "text", "text": structured_text}
            ]
        })
        
        return messages

    def generate_response_stream(self, audio_array, system_prompt):
        # 1. Format the messages with cross-lingual guards and text-only history
        messages = self._format_prompt(system_prompt)
        
        # 2. Apply template
        prompt = self.processor.apply_chat_template(
            messages, 
            tokenize=False, 
            add_generation_prompt=True
        )
        
        # 3. Process inputs (Audio is ONLY mapped to the current turn's <audio> tag)
        try:
            inputs = self.processor(text=prompt, audio=audio_array, return_tensors="pt", sampling_rate=self.sample_rate).to(self.device)
        except TypeError:
            inputs = self.processor(text=prompt, audios=audio_array, return_tensors="pt", sampling_rate=self.sample_rate).to(self.device)
            
        # 4. Setup the asynchronous streamer. skip_prompt=True ensures we don't output history/prompts
        streamer = TextIteratorStreamer(
            self.processor.tokenizer, 
            skip_prompt=True, 
            skip_special_tokens=True
        )
        
        # 5. Configure generation kwargs
        generation_kwargs = dict(
            **inputs, 
            streamer=streamer, 
            max_new_tokens=512, 
            temperature=0.7,
            do_sample=True,
            top_p=0.95
        )
        
        # 6. Launch generation in a non-blocking background thread
        thread = Thread(target=self.model.generate, kwargs=generation_kwargs)
        thread.start()
        
        # 7. Yield tokens live as they are generated by the model
        for new_token in streamer:
            # We yield ONLY the newly generated characters
            yield new_token
            
    def update_history(self, final_transcription, final_response):
        """Public helper to push verified strings back into history after the stream finishes."""
        # We store history as simple strings to prevent multimodal bloat
        if final_transcription and final_response:
             self.history.append({"role": "user", "content": final_transcription})
             self.history.append({"role": "assistant", "content": final_response})
             
             # Memory protection: Cap history at 5 turns (10 messages) to prevent slow-down
             if len(self.history) > 10:
                 self.history = self.history[-10:]
